package surplus;

import javax.swing.JOptionPane;
import java.sql.*;

public class SignUp extends javax.swing.JFrame {

    PreparedStatement pst = null;

    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
     */

    /**
     *
     * @author Riddhi
     */
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        fusername = new javax.swing.JTextField();
        fmobile = new javax.swing.JTextField();
        faddress = new javax.swing.JTextField();
        fsignup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fpassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("SIGN UP ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 16, 175, 55));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("NAME :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 110, 66, 33));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 700, 15));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("MOBILE NO. :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 165, -1, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("ADDRESS :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 221, 96, 32));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("USERNAME :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 280, 96, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("PASSWORD :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 324, 96, 38));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 110, 314, 37));

        fusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusernameActionPerformed(evt);
            }
        });
        getContentPane().add(fusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 280, 314, 36));

        fmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmobileActionPerformed(evt);
            }
        });
        getContentPane().add(fmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 167, 314, 36));

        faddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faddressActionPerformed(evt);
            }
        });
        getContentPane().add(faddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 314, 36));

        fsignup.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        fsignup.setText("SIGN UP");
        fsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsignupActionPerformed(evt);
            }
        });
        getContentPane().add(fsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 122, 54));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Already Signed Up ?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 130, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 90, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross3.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 50, 50));

        fpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 310, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xyz.LARGE2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fusernameActionPerformed

    private void fmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmobileActionPerformed

    private void faddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faddressActionPerformed

    private void fsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsignupActionPerformed
        if (fname.getText().isEmpty() || fusername.getText().isEmpty() || fpassword.getText().isEmpty()
                || fmobile.getText().isEmpty() || faddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
            return;
        }

            String name = fname.getText();
            String username = fusername.getText();
            String password = fpassword.getText();
            String mobile = fmobile.getText();
            String address = faddress.getText();

                String query = "insert into signup values('" + name + "','" + mobile + "','" + username + "','" + password + "','" + address + "')";
                try {
                    ConnectionProvider c = new ConnectionProvider();
                    c.s.executeUpdate(query);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
                UserLogin e = new UserLogin();
                e.setVisible(true);

                this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_fsignupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Welcomepg ve = new Welcomepg();
        ve.setVisible(true);                            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserLogin lo = new UserLogin();
        lo.setVisible(true);                            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SignUp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField faddress;
    private javax.swing.JTextField fmobile;
    private javax.swing.JTextField fname;
    private javax.swing.JPasswordField fpassword;
    private javax.swing.JButton fsignup;
    private javax.swing.JTextField fusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
